### ISSUE TITLE
Redraw TileLayer

### ISSUE THREAD

**Issue by bwyss** [ursudio/webgl-heatmap-leaflet#11]
I would like to be able to redraw a heatmap tilelayer. Not sure why it's not working, I was expeting the redraw method to be available.
example:

heatmap = new L.TileLayer.WebGLHeatMap({
        size: heatmapSize,
    });

After some event ...
heatmap.redraw();
...

I am getting: "heatmap.redraw is not a function"

**Comment by bozdoz** [comment]
Try `heatmap.update()`

**Comment by bwyss** [comment]
I tried heatmap.update(), but no dice

**Comment by bozdoz** [comment]
That redraws the webgl canvas. Do you have some code I could see?

**Comment by bozdoz** [comment]
New method is simply `heatmap.draw()`
