### ISSUE TITLE
Heatmap Legend

### ISSUE THREAD

**Issue by bwyss** [ursudio/webgl-heatmap-leaflet#12]
I am trying to find a way to create a dynamic legend for layers that are rendered with the heatmap plugin.
Maybe this is a feature request. 
Is there a way to capture the WebGL canvas color attributes so that I can build a legend?

**Comment by bozdoz** [comment]
Not really sure how to do that.  It's in the webgl library on line 937, if you want to do something with it: https://github.com/ursudio/webgl-heatmap-leaflet/blob/master/js/webgl-heatmap.js#L937

**Comment by bwyss** [comment]
I was thinking that another approach to this could be to provide the user with a bit interactivity. Perhaps a mouse hover event that would render the intensity value. Do you have any ideas about how to accomplish this?

**Comment by bozdoz** [comment]
I have thought about this problem before. It has more to do with the webgl
heatmap library than the plugin for leaflet, which this repo is. I don't
know enough about webgl to accomplish it. Sorry
