### ISSUE TITLE
several layers

### ISSUE THREAD

**Issue by bjjclimbin** [ursudio/webgl-heatmap-leaflet#14]
Hello.

I made an integration with leaflet, the purpose of the overall integration is to print a heatmap that will mark the points located on a  ground overlay (this overlay is referred from a kml file) . the problem is that the heatmap is shown behind the overlay layer thus not showing the needed information.

**Comment by bozdoz** [comment]
Add the ground overlay before the heatmap overlay, or adjust the z index with JavaScript/CSS:

example: `heatmap.canvas.style.zIndex = 10;`
