### ISSUE TITLE
question performance

### ISSUE THREAD

**Issue by geraldstanje** [ursudio/webgl-heatmap-leaflet#16]
Hi,

first of all: great lib.

In your example I get the following error:
```
(index):190 Uncaught TypeError: L.TileLayer.WebGLHeatMap is not a constructor
```

see: 

how many points can you add to the heatmap?

**Comment by bozdoz** [comment]
See readme:

I have changed the variable to L.WebGLHeatMap.  You can use it like this: `new L.WebGLHeatMap( options );`, or like this: `L.webGLHeatMap( options );`

**Comment by geraldstanje** [comment]
thanks for the info. I looked at this example, which seems not to be updated: http://ursudio.com/webgl-heatmap-leaflet/

how many points can you add to the heatmap? can you add new points on the fly and update the heatmap?

**Comment by bozdoz** [comment]
Right, I haven't altered the site in awhile.  

You can read up on the webgl heatmap performance here: http://codeflow.org/entries/2013/feb/04/high-performance-js-heatmaps/

Claims to handle about 500,000 points per second.  So, yes, you should be able to add up to 500,000 new points on the fly.

**Comment by geraldstanje** [comment]
@bozdoz thanks for the info. 
can you set the radius of influence for each data point? (see: https://developers.google.com/maps/documentation/javascript/heatmaplayer#customize_a_heatmap_layer)? 
how many pixels need to be within a radius to form a red point in the heatmap, is that parameter adjustable?
