### ISSUE TITLE
Heatmaps Do Not Work With Leaflet 1.0.0 RC 3

### ISSUE THREAD

**Issue by gordonbanderson** [ursudio/webgl-heatmap-leaflet#17]
I was just wondering if there are any plans to upgrade this plugin to work with Leaflet 1.0.0?

Getting this error, it works with 0.7.7 as expected.

```TypeError: t is undefined
	

...able()},whenReady:function(t,e){return this._loaded?t.call(e||this,{target:this}...```

**Comment by bozdoz** [comment]
Yeah, I can definitely take a look at that shortly.  Thanks for the heads up!

**Comment by gordonbanderson** [comment]
That would be orsome :)

**Comment by bhaskarvk** [comment]
+1

**Comment by bozdoz** [comment]
Done.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10082137-173281661_31-s1-v1.png?transparent=1&width=246)
