### ISSUE TITLE
spot size and zoom

### ISSUE THREAD

**Issue by dagatsoin** [ursudio/webgl-heatmap-leaflet#7]
Hello,

how could I have a fixed size spot (in pixel)  so when I zoom the heatmap are refresh and show me a more detailled aspect.
I don't want [that](http://tombatossals.github.io/angular-leaflet-directive/examples/heatmap-example.html) when I zoom, I want [that](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-heat/)

EDIT : reformulated my issue

**Comment by bozdoz** [comment]
So, you don't want it to maintain the actual area size or color?  You want it to shrink when zoomed in and grow then zoomed out?

**Comment by dagatsoin** [comment]
Yep exactly.

**Comment by bozdoz** [comment]
I suppose I could add an option to disable that.
