### ISSUE TITLE
Updating heatmap without zooming

### ISSUE THREAD

**Issue by alexcroox** [ursudio/webgl-heatmap-leaflet#8]
I want the heatmap to update without zooming, looking at the source it seems I should be able to call update() but this fails
```
map.heatmap = new L.TileLayer.WebGLHeatMap({
        size: 3000, 
        autoresize: true,
        opacity: 0.8
 });
```

`map.heatmap.update();`

`Uncaught TypeError: Cannot read property '_resizeRequest' of undefined`

It seems like the scope of `this` inside of `_plot` is causing some issues.

**Comment by bozdoz** [comment]
Hmm. I tested, but haven't been able to reproduce this error.  Do you have more example code for me to look at?

**Comment by bozdoz** [comment]
Probably an issue with leaflet versions.  This plugin now supports Leaflet version 0.7.7.
